version: '3.8'

services:
  nats-server: 
    image: nats
    ports:
      - "8222:8222"
  
  database:
    image: postgres:16.9-alpine3.21
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    ports:
      - "${DB_PORT}:5432"